All three homework task done. Commiting and pushing.
Sibronas/coherent-homework pull request #1
Opened 2021-12-02 11:24 UTC by Sibronas

2021-12-03 12:42 UTC, rkireevLT requested changes

2021-12-03 12:42 UTC, rkireevLT commented on Homework1/TaskOne/TaskOne/Program.cs
> +                if (numberInTernary.ToCharArray().Count(x => x == '2') == 2)
remove ToCharArray cast it is not needed

2021-12-03 12:42 UTC, rkireevLT commented on Homework1/TaskOne/TaskOne/Program.cs
> +            if (number is 0) return "0";
envelope if is curly braces even when one-liner inside. 
if (number is 0) 
{
 return "0";
}

2021-12-03 12:42 UTC, rkireevLT commented on Homework1/TaskOne/TaskOne/Program.cs
> +                if (temp < 0) number += 1;
It may not be below 0, just call tempList.Add(temp);

2021-12-09 11:35 UTC, radislavkireev approved these changes

2021-12-09 11:36 UTC, rkireevLT approved these changes

2021-12-09 15:31 UTC, merged